# This workflow detects the changed packages and run the
# corresponding tests. Additionally, it triggers
# the `deploy-main-review-env` workflow when ran on `main`.

name: Deploy main

on:
  push:
    branches:
      - 'main'

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: yarn

      - name: Install dependencies
        run: corepack enable && yarn install --immutable

      - name: Build
        run: yarn build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist
